name: flutter_app_test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.8

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  get_it: ^8.0.2
  get: ^4.6.6
  drag_select_grid_view: ^0.6.2
  photo_manager: ^3.7.1
  permission_handler: ^12.0.0+1
  transparent_image: ^2.0.0
  dots_indicator: ^2.1.1
  wechat_assets_picker: ^9.0.2
  fast_image_resizer: ^0.0.2
  dropdown_button2: ^2.3.9
  device_info_plus: ^11.1.1
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.1
  intl: ^0.20.2
  shared_preferences: ^2.0.18
  persistent_bottom_nav_bar_v2: ^5.3.1
  flutter_branch_sdk: ^8.5.0
  infinite_scroll_pagination: ^5.1.0
  url_launcher: ^6.3.2
  share_plus: ^12.0.1 # 공유 기능
  geolocator: ^14.0.2 # 위치 서비스

  # 커스텀 스킴 딥링크
  app_links: ^6.4.1

  # UI
  flutter_animate: ^4.5.2
  video_player: ^2.8.2
  cached_network_image: ^3.4.1
  flutter_easyloading: ^3.0.5         # 로딩 UI 처리
  image_picker: ^1.1.2
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  focus_detector_v2: ^3.1.0+1
  webview_flutter: ^4.13.0
  flutter_html: ^3.0.0
  flutter_inappwebview: ^6.1.5
  table_calendar: ^3.2.0 # 달력
  google_maps_flutter: ^2.14.0 # 지도

  # Firebase
  firebase_core: ^3.15.0
  firebase_messaging: ^15.2.8

  # 로컬 알림
  flutter_local_notifications: ^19.3.0

  # 로그인
  kakao_flutter_sdk_user: ^1.9.5
  sign_in_with_apple: ^7.0.1
  google_sign_in: ^6.3.0

  photo_manager_image_provider: ^2.2.0

  path_provider: any

  flutter_hooks: ^0.21.2
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKR-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansKR-Black.ttf
          weight: 900
